import * as path from 'path';
import * as vscode from 'vscode';

const faIcons = [
	{ class: "ad", unicode: "f641", type: 'fas'},
	{ class: "address-book", unicode: "f2b9", type: 'fas'},
	{ class: "address-card", unicode: "f2bb", type: 'fas'},
	{ class: "adjust", unicode: "f042", type: 'fas'},
	{ class: "air-freshener", unicode: "f5d0", type: 'fas'},
	{ class: "align-center", unicode: "f037", type: 'fas'},
	{ class: "align-justify", unicode: "f039", type: 'fas'},
	{ class: "align-left", unicode: "f036", type: 'fas'},
	{ class: "align-right", unicode: "f038", type: 'fas'},
	{ class: "allergies", unicode: "f461", type: 'fas'},
	{ class: "ambulance", unicode: "f0f9", type: 'fas'},
	{ class: "american-sign-language-interpreting", unicode: "f2a3", type: 'fas'},
	{ class: "anchor", unicode: "f13d", type: 'fas'},
	{ class: "angle-double-down", unicode: "f103", type: 'fas'},
	{ class: "angle-double-left", unicode: "f100", type: 'fas'},
	{ class: "angle-double-right", unicode: "f101", type: 'fas'},
	{ class: "angle-double-up", unicode: "f102", type: 'fas'},
	{ class: "angle-down", unicode: "f107", type: 'fas'},
	{ class: "angle-left", unicode: "f104", type: 'fas'},
	{ class: "angle-right", unicode: "f105", type: 'fas'},
	{ class: "angle-up", unicode: "f106", type: 'fas'},
	{ class: "angry", unicode: "f556", type: 'fas'},
	{ class: "ankh", unicode: "f644", type: 'fas'},
	{ class: "apple-alt", unicode: "f5d1", type: 'fas'},
	{ class: "archive", unicode: "f187", type: 'fas'},
	{ class: "archway", unicode: "f557", type: 'fas'},
	{ class: "arrow-alt-circle-down", unicode: "f358", type: 'fas'},
	{ class: "arrow-alt-circle-left", unicode: "f359", type: 'fas'},
	{ class: "arrow-alt-circle-right", unicode: "f35a", type: 'fas'},
	{ class: "arrow-alt-circle-up", unicode: "f35b", type: 'fas'},
	{ class: "arrow-circle-down", unicode: "f0ab", type: 'fas'},
	{ class: "arrow-circle-left", unicode: "f0a8", type: 'fas'},
	{ class: "arrow-circle-right", unicode: "f0a9", type: 'fas'},
	{ class: "arrow-circle-up", unicode: "f0aa", type: 'fas'},
	{ class: "arrow-down", unicode: "f063", type: 'fas'},
	{ class: "arrow-left", unicode: "f060", type: 'fas'},
	{ class: "arrow-right", unicode: "f061", type: 'fas'},
	{ class: "arrow-up", unicode: "f062", type: 'fas'},
	{ class: "arrows-alt", unicode: "f0b2", type: 'fas'},
	{ class: "arrows-alt-h", unicode: "f337", type: 'fas'},
	{ class: "arrows-alt-v", unicode: "f338", type: 'fas'},
	{ class: "assistive-listening-systems", unicode: "f2a2", type: 'fas'},
	{ class: "asterisk", unicode: "f069", type: 'fas'},
	{ class: "at", unicode: "f1fa", type: 'fas'},
	{ class: "atlas", unicode: "f558", type: 'fas'},
	{ class: "atom", unicode: "f5d2", type: 'fas'},
	{ class: "audio-description", unicode: "f29e", type: 'fas'},
	{ class: "award", unicode: "f559", type: 'fas'},
	{ class: "baby", unicode: "f77c", type: 'fas'},
	{ class: "baby-carriage", unicode: "f77d", type: 'fas'},
	{ class: "backspace", unicode: "f55a", type: 'fas'},
	{ class: "backward", unicode: "f04a", type: 'fas'},
	{ class: "bacon", unicode: "f7e5", type: 'fas'},
	{ class: "balance-scale", unicode: "f24e", type: 'fas'},
	{ class: "ban", unicode: "f05e", type: 'fas'},
	{ class: "band-aid", unicode: "f462", type: 'fas'},
	{ class: "barcode", unicode: "f02a", type: 'fas'},
	{ class: "bars", unicode: "f0c9", type: 'fas'},
	{ class: "baseball-ball", unicode: "f433", type: 'fas'},
	{ class: "basketball-ball", unicode: "f434", type: 'fas'},
	{ class: "bath", unicode: "f2cd", type: 'fas'},
	{ class: "battery-empty", unicode: "f244", type: 'fas'},
	{ class: "battery-full", unicode: "f240", type: 'fas'},
	{ class: "battery-half", unicode: "f242", type: 'fas'},
	{ class: "battery-quarter", unicode: "f243", type: 'fas'},
	{ class: "battery-three-quarters", unicode: "f241", type: 'fas'},
	{ class: "bed", unicode: "f236", type: 'fas'},
	{ class: "beer", unicode: "f0fc", type: 'fas'},
	{ class: "bell", unicode: "f0f3", type: 'fas'},
	{ class: "bell-slash", unicode: "f1f6", type: 'fas'},
	{ class: "bezier-curve", unicode: "f55b", type: 'fas'},
	{ class: "bible", unicode: "f647", type: 'fas'},
	{ class: "bicycle", unicode: "f206", type: 'fas'},
	{ class: "binoculars", unicode: "f1e5", type: 'fas'},
	{ class: "biohazard", unicode: "f780", type: 'fas'},
	{ class: "birthday-cake", unicode: "f1fd", type: 'fas'},
	{ class: "blender", unicode: "f517", type: 'fas'},
	{ class: "blender-phone", unicode: "f6b6", type: 'fas'},
	{ class: "blind", unicode: "f29d", type: 'fas'},
	{ class: "blog", unicode: "f781", type: 'fas'},
	{ class: "bold", unicode: "f032", type: 'fas'},
	{ class: "bolt", unicode: "f0e7", type: 'fas'},
	{ class: "bomb", unicode: "f1e2", type: 'fas'},
	{ class: "bone", unicode: "f5d7", type: 'fas'},
	{ class: "bong", unicode: "f55c", type: 'fas'},
	{ class: "book", unicode: "f02d", type: 'fas'},
	{ class: "book-dead", unicode: "f6b7", type: 'fas'},
	{ class: "book-medical", unicode: "f7e6", type: 'fas'},
	{ class: "book-open", unicode: "f518", type: 'fas'},
	{ class: "book-reader", unicode: "f5da", type: 'fas'},
	{ class: "bookmark", unicode: "f02e", type: 'fas'},
	{ class: "bowling-ball", unicode: "f436", type: 'fas'},
	{ class: "box", unicode: "f466", type: 'fas'},
	{ class: "box-open", unicode: "f49e", type: 'fas'},
	{ class: "boxes", unicode: "f468", type: 'fas'},
	{ class: "braille", unicode: "f2a1", type: 'fas'},
	{ class: "brain", unicode: "f5dc", type: 'fas'},
	{ class: "bread-slice", unicode: "f7ec", type: 'fas'},
	{ class: "briefcase", unicode: "f0b1", type: 'fas'},
	{ class: "briefcase-medical", unicode: "f469", type: 'fas'},
	{ class: "broadcast-tower", unicode: "f519", type: 'fas'},
	{ class: "broom", unicode: "f51a", type: 'fas'},
	{ class: "brush", unicode: "f55d", type: 'fas'},
	{ class: "bug", unicode: "f188", type: 'fas'},
	{ class: "building", unicode: "f1ad", type: 'fas'},
	{ class: "bullhorn", unicode: "f0a1", type: 'fas'},
	{ class: "bullseye", unicode: "f140", type: 'fas'},
	{ class: "burn", unicode: "f46a", type: 'fas'},
	{ class: "bus", unicode: "f207", type: 'fas'},
	{ class: "bus-alt", unicode: "f55e", type: 'fas'},
	{ class: "business-time", unicode: "f64a", type: 'fas'},
	{ class: "calculator", unicode: "f1ec", type: 'fas'},
	{ class: "calendar", unicode: "f133", type: 'fas'},
	{ class: "calendar-alt", unicode: "f073", type: 'fas'},
	{ class: "calendar-check", unicode: "f274", type: 'fas'},
	{ class: "calendar-day", unicode: "f783", type: 'fas'},
	{ class: "calendar-minus", unicode: "f272", type: 'fas'},
	{ class: "calendar-plus", unicode: "f271", type: 'fas'},
	{ class: "calendar-times", unicode: "f273", type: 'fas'},
	{ class: "calendar-week", unicode: "f784", type: 'fas'},
	{ class: "camera", unicode: "f030", type: 'fas'},
	{ class: "camera-retro", unicode: "f083", type: 'fas'},
	{ class: "campground", unicode: "f6bb", type: 'fas'},
	{ class: "candy-cane", unicode: "f786", type: 'fas'},
	{ class: "cannabis", unicode: "f55f", type: 'fas'},
	{ class: "capsules", unicode: "f46b", type: 'fas'},
	{ class: "car", unicode: "f1b9", type: 'fas'},
	{ class: "car-alt", unicode: "f5de", type: 'fas'},
	{ class: "car-battery", unicode: "f5df", type: 'fas'},
	{ class: "car-crash", unicode: "f5e1", type: 'fas'},
	{ class: "car-side", unicode: "f5e4", type: 'fas'},
	{ class: "caret-down", unicode: "f0d7", type: 'fas'},
	{ class: "caret-left", unicode: "f0d9", type: 'fas'},
	{ class: "caret-right", unicode: "f0da", type: 'fas'},
	{ class: "caret-square-down", unicode: "f150", type: 'fas'},
	{ class: "caret-square-left", unicode: "f191", type: 'fas'},
	{ class: "caret-square-right", unicode: "f152", type: 'fas'},
	{ class: "caret-square-up", unicode: "f151", type: 'fas'},
	{ class: "caret-up", unicode: "f0d8", type: 'fas'},
	{ class: "carrot", unicode: "f787", type: 'fas'},
	{ class: "cart-arrow-down", unicode: "f218", type: 'fas'},
	{ class: "cart-plus", unicode: "f217", type: 'fas'},
	{ class: "cash-register", unicode: "f788", type: 'fas'},
	{ class: "cat", unicode: "f6be", type: 'fas'},
	{ class: "certificate", unicode: "f0a3", type: 'fas'},
	{ class: "chair", unicode: "f6c0", type: 'fas'},
	{ class: "chalkboard", unicode: "f51b", type: 'fas'},
	{ class: "chalkboard-teacher", unicode: "f51c", type: 'fas'},
	{ class: "charging-station", unicode: "f5e7", type: 'fas'},
	{ class: "chart-area", unicode: "f1fe", type: 'fas'},
	{ class: "chart-bar", unicode: "f080", type: 'fas'},
	{ class: "chart-line", unicode: "f201", type: 'fas'},
	{ class: "chart-pie", unicode: "f200", type: 'fas'},
	{ class: "check", unicode: "f00c", type: 'fas'},
	{ class: "check-circle", unicode: "f058", type: 'fas'},
	{ class: "check-double", unicode: "f560", type: 'fas'},
	{ class: "check-square", unicode: "f14a", type: 'fas'},
	{ class: "cheese", unicode: "f7ef", type: 'fas'},
	{ class: "chess", unicode: "f439", type: 'fas'},
	{ class: "chess-bishop", unicode: "f43a", type: 'fas'},
	{ class: "chess-board", unicode: "f43c", type: 'fas'},
	{ class: "chess-king", unicode: "f43f", type: 'fas'},
	{ class: "chess-knight", unicode: "f441", type: 'fas'},
	{ class: "chess-pawn", unicode: "f443", type: 'fas'},
	{ class: "chess-queen", unicode: "f445", type: 'fas'},
	{ class: "chess-rook", unicode: "f447", type: 'fas'},
	{ class: "chevron-circle-down", unicode: "f13a", type: 'fas'},
	{ class: "chevron-circle-left", unicode: "f137", type: 'fas'},
	{ class: "chevron-circle-right", unicode: "f138", type: 'fas'},
	{ class: "chevron-circle-up", unicode: "f139", type: 'fas'},
	{ class: "chevron-down", unicode: "f078", type: 'fas'},
	{ class: "chevron-left", unicode: "f053", type: 'fas'},
	{ class: "chevron-right", unicode: "f054", type: 'fas'},
	{ class: "chevron-up", unicode: "f077", type: 'fas'},
	{ class: "child", unicode: "f1ae", type: 'fas'},
	{ class: "church", unicode: "f51d", type: 'fas'},
	{ class: "circle", unicode: "f111", type: 'fas'},
	{ class: "circle-notch", unicode: "f1ce", type: 'fas'},
	{ class: "city", unicode: "f64f", type: 'fas'},
	{ class: "clinic-medical", unicode: "f7f2", type: 'fas'},
	{ class: "clipboard", unicode: "f328", type: 'fas'},
	{ class: "clipboard-check", unicode: "f46c", type: 'fas'},
	{ class: "clipboard-list", unicode: "f46d", type: 'fas'},
	{ class: "clock", unicode: "f017", type: 'fas'},
	{ class: "clone", unicode: "f24d", type: 'fas'},
	{ class: "closed-captioning", unicode: "f20a", type: 'fas'},
	{ class: "cloud", unicode: "f0c2", type: 'fas'},
	{ class: "cloud-download-alt", unicode: "f381", type: 'fas'},
	{ class: "cloud-meatball", unicode: "f73b", type: 'fas'},
	{ class: "cloud-moon", unicode: "f6c3", type: 'fas'},
	{ class: "cloud-moon-rain", unicode: "f73c", type: 'fas'},
	{ class: "cloud-rain", unicode: "f73d", type: 'fas'},
	{ class: "cloud-showers-heavy", unicode: "f740", type: 'fas'},
	{ class: "cloud-sun", unicode: "f6c4", type: 'fas'},
	{ class: "cloud-sun-rain", unicode: "f743", type: 'fas'},
	{ class: "cloud-upload-alt", unicode: "f382", type: 'fas'},
	{ class: "cocktail", unicode: "f561", type: 'fas'},
	{ class: "code", unicode: "f121", type: 'fas'},
	{ class: "code-branch", unicode: "f126", type: 'fas'},
	{ class: "coffee", unicode: "f0f4", type: 'fas'},
	{ class: "cog", unicode: "f013", type: 'fas'},
	{ class: "cogs", unicode: "f085", type: 'fas'},
	{ class: "coins", unicode: "f51e", type: 'fas'},
	{ class: "columns", unicode: "f0db", type: 'fas'},
	{ class: "comment", unicode: "f075", type: 'fas'},
	{ class: "comment-alt", unicode: "f27a", type: 'fas'},
	{ class: "comment-dollar", unicode: "f651", type: 'fas'},
	{ class: "comment-dots", unicode: "f4ad", type: 'fas'},
	{ class: "comment-medical", unicode: "f7f5", type: 'fas'},
	{ class: "comment-slash", unicode: "f4b3", type: 'fas'},
	{ class: "comments", unicode: "f086", type: 'fas'},
	{ class: "comments-dollar", unicode: "f653", type: 'fas'},
	{ class: "compact-disc", unicode: "f51f", type: 'fas'},
	{ class: "compass", unicode: "f14e", type: 'fas'},
	{ class: "compress", unicode: "f066", type: 'fas'},
	{ class: "compress-arrows-alt", unicode: "f78c", type: 'fas'},
	{ class: "concierge-bell", unicode: "f562", type: 'fas'},
	{ class: "cookie", unicode: "f563", type: 'fas'},
	{ class: "cookie-bite", unicode: "f564", type: 'fas'},
	{ class: "copy", unicode: "f0c5", type: 'fas'},
	{ class: "copyright", unicode: "f1f9", type: 'fas'},
	{ class: "couch", unicode: "f4b8", type: 'fas'},
	{ class: "credit-card", unicode: "f09d", type: 'fas'},
	{ class: "crop", unicode: "f125", type: 'fas'},
	{ class: "crop-alt", unicode: "f565", type: 'fas'},
	{ class: "cross", unicode: "f654", type: 'fas'},
	{ class: "crosshairs", unicode: "f05b", type: 'fas'},
	{ class: "crow", unicode: "f520", type: 'fas'},
	{ class: "crown", unicode: "f521", type: 'fas'},
	{ class: "crutch", unicode: "f7f7", type: 'fas'},
	{ class: "cube", unicode: "f1b2", type: 'fas'},
	{ class: "cubes", unicode: "f1b3", type: 'fas'},
	{ class: "cut", unicode: "f0c4", type: 'fas'},
	{ class: "database", unicode: "f1c0", type: 'fas'},
	{ class: "deaf", unicode: "f2a4", type: 'fas'},
	{ class: "democrat", unicode: "f747", type: 'fas'},
	{ class: "desktop", unicode: "f108", type: 'fas'},
	{ class: "dharmachakra", unicode: "f655", type: 'fas'},
	{ class: "diagnoses", unicode: "f470", type: 'fas'},
	{ class: "dice", unicode: "f522", type: 'fas'},
	{ class: "dice-d20", unicode: "f6cf", type: 'fas'},
	{ class: "dice-d6", unicode: "f6d1", type: 'fas'},
	{ class: "dice-five", unicode: "f523", type: 'fas'},
	{ class: "dice-four", unicode: "f524", type: 'fas'},
	{ class: "dice-one", unicode: "f525", type: 'fas'},
	{ class: "dice-six", unicode: "f526", type: 'fas'},
	{ class: "dice-three", unicode: "f527", type: 'fas'},
	{ class: "dice-two", unicode: "f528", type: 'fas'},
	{ class: "digital-tachograph", unicode: "f566", type: 'fas'},
	{ class: "directions", unicode: "f5eb", type: 'fas'},
	{ class: "divide", unicode: "f529", type: 'fas'},
	{ class: "dizzy", unicode: "f567", type: 'fas'},
	{ class: "dna", unicode: "f471", type: 'fas'},
	{ class: "dog", unicode: "f6d3", type: 'fas'},
	{ class: "dollar-sign", unicode: "f155", type: 'fas'},
	{ class: "dolly", unicode: "f472", type: 'fas'},
	{ class: "dolly-flatbed", unicode: "f474", type: 'fas'},
	{ class: "donate", unicode: "f4b9", type: 'fas'},
	{ class: "door-closed", unicode: "f52a", type: 'fas'},
	{ class: "door-open", unicode: "f52b", type: 'fas'},
	{ class: "dot-circle", unicode: "f192", type: 'fas'},
	{ class: "dove", unicode: "f4ba", type: 'fas'},
	{ class: "download", unicode: "f019", type: 'fas'},
	{ class: "drafting-compass", unicode: "f568", type: 'fas'},
	{ class: "dragon", unicode: "f6d5", type: 'fas'},
	{ class: "draw-polygon", unicode: "f5ee", type: 'fas'},
	{ class: "drum", unicode: "f569", type: 'fas'},
	{ class: "drum-steelpan", unicode: "f56a", type: 'fas'},
	{ class: "drumstick-bite", unicode: "f6d7", type: 'fas'},
	{ class: "dumbbell", unicode: "f44b", type: 'fas'},
	{ class: "dumpster", unicode: "f793", type: 'fas'},
	{ class: "dumpster-fire", unicode: "f794", type: 'fas'},
	{ class: "dungeon", unicode: "f6d9", type: 'fas'},
	{ class: "edit", unicode: "f044", type: 'fas'},
	{ class: "egg", unicode: "f7fb", type: 'fas'},
	{ class: "eject", unicode: "f052", type: 'fas'},
	{ class: "ellipsis-h", unicode: "f141", type: 'fas'},
	{ class: "ellipsis-v", unicode: "f142", type: 'fas'},
	{ class: "envelope", unicode: "f0e0", type: 'fas'},
	{ class: "envelope-open", unicode: "f2b6", type: 'fas'},
	{ class: "envelope-open-text", unicode: "f658", type: 'fas'},
	{ class: "envelope-square", unicode: "f199", type: 'fas'},
	{ class: "equals", unicode: "f52c", type: 'fas'},
	{ class: "eraser", unicode: "f12d", type: 'fas'},
	{ class: "ethernet", unicode: "f796", type: 'fas'},
	{ class: "euro-sign", unicode: "f153", type: 'fas'},
	{ class: "exchange-alt", unicode: "f362", type: 'fas'},
	{ class: "exclamation", unicode: "f12a", type: 'fas'},
	{ class: "exclamation-circle", unicode: "f06a", type: 'fas'},
	{ class: "exclamation-triangle", unicode: "f071", type: 'fas'},
	{ class: "expand", unicode: "f065", type: 'fas'},
	{ class: "expand-arrows-alt", unicode: "f31e", type: 'fas'},
	{ class: "external-link-alt", unicode: "f35d", type: 'fas'},
	{ class: "external-link-square-alt", unicode: "f360", type: 'fas'},
	{ class: "eye", unicode: "f06e", type: 'fas'},
	{ class: "eye-dropper", unicode: "f1fb", type: 'fas'},
	{ class: "eye-slash", unicode: "f070", type: 'fas'},
	{ class: "fast-backward", unicode: "f049", type: 'fas'},
	{ class: "fast-forward", unicode: "f050", type: 'fas'},
	{ class: "fax", unicode: "f1ac", type: 'fas'},
	{ class: "feather", unicode: "f52d", type: 'fas'},
	{ class: "feather-alt", unicode: "f56b", type: 'fas'},
	{ class: "female", unicode: "f182", type: 'fas'},
	{ class: "fighter-jet", unicode: "f0fb", type: 'fas'},
	{ class: "file", unicode: "f15b", type: 'fas'},
	{ class: "file-alt", unicode: "f15c", type: 'fas'},
	{ class: "file-archive", unicode: "f1c6", type: 'fas'},
	{ class: "file-audio", unicode: "f1c7", type: 'fas'},
	{ class: "file-code", unicode: "f1c9", type: 'fas'},
	{ class: "file-contract", unicode: "f56c", type: 'fas'},
	{ class: "file-csv", unicode: "f6dd", type: 'fas'},
	{ class: "file-download", unicode: "f56d", type: 'fas'},
	{ class: "file-excel", unicode: "f1c3", type: 'fas'},
	{ class: "file-export", unicode: "f56e", type: 'fas'},
	{ class: "file-image", unicode: "f1c5", type: 'fas'},
	{ class: "file-import", unicode: "f56f", type: 'fas'},
	{ class: "file-invoice", unicode: "f570", type: 'fas'},
	{ class: "file-invoice-dollar", unicode: "f571", type: 'fas'},
	{ class: "file-medical", unicode: "f477", type: 'fas'},
	{ class: "file-medical-alt", unicode: "f478", type: 'fas'},
	{ class: "file-pdf", unicode: "f1c1", type: 'fas'},
	{ class: "file-powerpoint", unicode: "f1c4", type: 'fas'},
	{ class: "file-prescription", unicode: "f572", type: 'fas'},
	{ class: "file-signature", unicode: "f573", type: 'fas'},
	{ class: "file-upload", unicode: "f574", type: 'fas'},
	{ class: "file-video", unicode: "f1c8", type: 'fas'},
	{ class: "file-word", unicode: "f1c2", type: 'fas'},
	{ class: "fill", unicode: "f575", type: 'fas'},
	{ class: "fill-drip", unicode: "f576", type: 'fas'},
	{ class: "film", unicode: "f008", type: 'fas'},
	{ class: "filter", unicode: "f0b0", type: 'fas'},
	{ class: "fingerprint", unicode: "f577", type: 'fas'},
	{ class: "fire", unicode: "f06d", type: 'fas'},
	{ class: "fire-alt", unicode: "f7e4", type: 'fas'},
	{ class: "fire-extinguisher", unicode: "f134", type: 'fas'},
	{ class: "first-aid", unicode: "f479", type: 'fas'},
	{ class: "fish", unicode: "f578", type: 'fas'},
	{ class: "fist-raised", unicode: "f6de", type: 'fas'},
	{ class: "flag", unicode: "f024", type: 'fas'},
	{ class: "flag-checkered", unicode: "f11e", type: 'fas'},
	{ class: "flag-usa", unicode: "f74d", type: 'fas'},
	{ class: "flask", unicode: "f0c3", type: 'fas'},
	{ class: "flushed", unicode: "f579", type: 'fas'},
	{ class: "folder", unicode: "f07b", type: 'fas'},
	{ class: "folder-minus", unicode: "f65d", type: 'fas'},
	{ class: "folder-open", unicode: "f07c", type: 'fas'},
	{ class: "folder-plus", unicode: "f65e", type: 'fas'},
	{ class: "font", unicode: "f031", type: 'fas'},
	{ class: "football-ball", unicode: "f44e", type: 'fas'},
	{ class: "forward", unicode: "f04e", type: 'fas'},
	{ class: "frog", unicode: "f52e", type: 'fas'},
	{ class: "frown", unicode: "f119", type: 'fas'},
	{ class: "frown-open", unicode: "f57a", type: 'fas'},
	{ class: "funnel-dollar", unicode: "f662", type: 'fas'},
	{ class: "futbol", unicode: "f1e3", type: 'fas'},
	{ class: "gamepad", unicode: "f11b", type: 'fas'},
	{ class: "gas-pump", unicode: "f52f", type: 'fas'},
	{ class: "gavel", unicode: "f0e3", type: 'fas'},
	{ class: "gem", unicode: "f3a5", type: 'fas'},
	{ class: "genderless", unicode: "f22d", type: 'fas'},
	{ class: "ghost", unicode: "f6e2", type: 'fas'},
	{ class: "gift", unicode: "f06b", type: 'fas'},
	{ class: "gifts", unicode: "f79c", type: 'fas'},
	{ class: "glass-cheers", unicode: "f79f", type: 'fas'},
	{ class: "glass-martini", unicode: "f000", type: 'fas'},
	{ class: "glass-martini-alt", unicode: "f57b", type: 'fas'},
	{ class: "glass-whiskey", unicode: "f7a0", type: 'fas'},
	{ class: "glasses", unicode: "f530", type: 'fas'},
	{ class: "globe", unicode: "f0ac", type: 'fas'},
	{ class: "globe-africa", unicode: "f57c", type: 'fas'},
	{ class: "globe-americas", unicode: "f57d", type: 'fas'},
	{ class: "globe-asia", unicode: "f57e", type: 'fas'},
	{ class: "globe-europe", unicode: "f7a2", type: 'fas'},
	{ class: "golf-ball", unicode: "f450", type: 'fas'},
	{ class: "gopuram", unicode: "f664", type: 'fas'},
	{ class: "graduation-cap", unicode: "f19d", type: 'fas'},
	{ class: "greater-than", unicode: "f531", type: 'fas'},
	{ class: "greater-than-equal", unicode: "f532", type: 'fas'},
	{ class: "grimace", unicode: "f57f", type: 'fas'},
	{ class: "grin", unicode: "f580", type: 'fas'},
	{ class: "grin-alt", unicode: "f581", type: 'fas'},
	{ class: "grin-beam", unicode: "f582", type: 'fas'},
	{ class: "grin-beam-sweat", unicode: "f583", type: 'fas'},
	{ class: "grin-hearts", unicode: "f584", type: 'fas'},
	{ class: "grin-squint", unicode: "f585", type: 'fas'},
	{ class: "grin-squint-tears", unicode: "f586", type: 'fas'},
	{ class: "grin-stars", unicode: "f587", type: 'fas'},
	{ class: "grin-tears", unicode: "f588", type: 'fas'},
	{ class: "grin-tongue", unicode: "f589", type: 'fas'},
	{ class: "grin-tongue-squint", unicode: "f58a", type: 'fas'},
	{ class: "grin-tongue-wink", unicode: "f58b", type: 'fas'},
	{ class: "grin-wink", unicode: "f58c", type: 'fas'},
	{ class: "grip-horizontal", unicode: "f58d", type: 'fas'},
	{ class: "grip-lines", unicode: "f7a4", type: 'fas'},
	{ class: "grip-lines-vertical", unicode: "f7a5", type: 'fas'},
	{ class: "grip-vertical", unicode: "f58e", type: 'fas'},
	{ class: "guitar", unicode: "f7a6", type: 'fas'},
	{ class: "h-square", unicode: "f0fd", type: 'fas'},
	{ class: "hamburger", unicode: "f805", type: 'fas'},
	{ class: "hammer", unicode: "f6e3", type: 'fas'},
	{ class: "hamsa", unicode: "f665", type: 'fas'},
	{ class: "hand-holding", unicode: "f4bd", type: 'fas'},
	{ class: "hand-holding-heart", unicode: "f4be", type: 'fas'},
	{ class: "hand-holding-usd", unicode: "f4c0", type: 'fas'},
	{ class: "hand-lizard", unicode: "f258", type: 'fas'},
	{ class: "hand-middle-finger", unicode: "f806", type: 'fas'},
	{ class: "hand-paper", unicode: "f256", type: 'fas'},
	{ class: "hand-peace", unicode: "f25b", type: 'fas'},
	{ class: "hand-point-down", unicode: "f0a7", type: 'fas'},
	{ class: "hand-point-left", unicode: "f0a5", type: 'fas'},
	{ class: "hand-point-right", unicode: "f0a4", type: 'fas'},
	{ class: "hand-point-up", unicode: "f0a6", type: 'fas'},
	{ class: "hand-pointer", unicode: "f25a", type: 'fas'},
	{ class: "hand-rock", unicode: "f255", type: 'fas'},
	{ class: "hand-scissors", unicode: "f257", type: 'fas'},
	{ class: "hand-spock", unicode: "f259", type: 'fas'},
	{ class: "hands", unicode: "f4c2", type: 'fas'},
	{ class: "hands-helping", unicode: "f4c4", type: 'fas'},
	{ class: "handshake", unicode: "f2b5", type: 'fas'},
	{ class: "hanukiah", unicode: "f6e6", type: 'fas'},
	{ class: "hard-hat", unicode: "f807", type: 'fas'},
	{ class: "hashtag", unicode: "f292", type: 'fas'},
	{ class: "hat-wizard", unicode: "f6e8", type: 'fas'},
	{ class: "haykal", unicode: "f666", type: 'fas'},
	{ class: "hdd", unicode: "f0a0", type: 'fas'},
	{ class: "heading", unicode: "f1dc", type: 'fas'},
	{ class: "headphones", unicode: "f025", type: 'fas'},
	{ class: "headphones-alt", unicode: "f58f", type: 'fas'},
	{ class: "headset", unicode: "f590", type: 'fas'},
	{ class: "heart", unicode: "f004", type: 'fas'},
	{ class: "heart-broken", unicode: "f7a9", type: 'fas'},
	{ class: "heartbeat", unicode: "f21e", type: 'fas'},
	{ class: "helicopter", unicode: "f533", type: 'fas'},
	{ class: "highlighter", unicode: "f591", type: 'fas'},
	{ class: "hiking", unicode: "f6ec", type: 'fas'},
	{ class: "hippo", unicode: "f6ed", type: 'fas'},
	{ class: "history", unicode: "f1da", type: 'fas'},
	{ class: "hockey-puck", unicode: "f453", type: 'fas'},
	{ class: "holly-berry", unicode: "f7aa", type: 'fas'},
	{ class: "home", unicode: "f015", type: 'fas'},
	{ class: "horse", unicode: "f6f0", type: 'fas'},
	{ class: "horse-head", unicode: "f7ab", type: 'fas'},
	{ class: "hospital", unicode: "f0f8", type: 'fas'},
	{ class: "hospital-alt", unicode: "f47d", type: 'fas'},
	{ class: "hospital-symbol", unicode: "f47e", type: 'fas'},
	{ class: "hot-tub", unicode: "f593", type: 'fas'},
	{ class: "hotdog", unicode: "f80f", type: 'fas'},
	{ class: "hotel", unicode: "f594", type: 'fas'},
	{ class: "hourglass", unicode: "f254", type: 'fas'},
	{ class: "hourglass-end", unicode: "f253", type: 'fas'},
	{ class: "hourglass-half", unicode: "f252", type: 'fas'},
	{ class: "hourglass-start", unicode: "f251", type: 'fas'},
	{ class: "house-damage", unicode: "f6f1", type: 'fas'},
	{ class: "hryvnia", unicode: "f6f2", type: 'fas'},
	{ class: "i-cursor", unicode: "f246", type: 'fas'},
	{ class: "ice-cream", unicode: "f810", type: 'fas'},
	{ class: "icicles", unicode: "f7ad", type: 'fas'},
	{ class: "id-badge", unicode: "f2c1", type: 'fas'},
	{ class: "id-card", unicode: "f2c2", type: 'fas'},
	{ class: "id-card-alt", unicode: "f47f", type: 'fas'},
	{ class: "igloo", unicode: "f7ae", type: 'fas'},
	{ class: "image", unicode: "f03e", type: 'fas'},
	{ class: "images", unicode: "f302", type: 'fas'},
	{ class: "inbox", unicode: "f01c", type: 'fas'},
	{ class: "indent", unicode: "f03c", type: 'fas'},
	{ class: "industry", unicode: "f275", type: 'fas'},
	{ class: "infinity", unicode: "f534", type: 'fas'},
	{ class: "info", unicode: "f129", type: 'fas'},
	{ class: "info-circle", unicode: "f05a", type: 'fas'},
	{ class: "italic", unicode: "f033", type: 'fas'},
	{ class: "jedi", unicode: "f669", type: 'fas'},
	{ class: "joint", unicode: "f595", type: 'fas'},
	{ class: "journal-whills", unicode: "f66a", type: 'fas'},
	{ class: "kaaba", unicode: "f66b", type: 'fas'},
	{ class: "key", unicode: "f084", type: 'fas'},
	{ class: "keyboard", unicode: "f11c", type: 'fas'},
	{ class: "khanda", unicode: "f66d", type: 'fas'},
	{ class: "kiss", unicode: "f596", type: 'fas'},
	{ class: "kiss-beam", unicode: "f597", type: 'fas'},
	{ class: "kiss-wink-heart", unicode: "f598", type: 'fas'},
	{ class: "kiwi-bird", unicode: "f535", type: 'fas'},
	{ class: "landmark", unicode: "f66f", type: 'fas'},
	{ class: "language", unicode: "f1ab", type: 'fas'},
	{ class: "laptop", unicode: "f109", type: 'fas'},
	{ class: "laptop-code", unicode: "f5fc", type: 'fas'},
	{ class: "laptop-medical", unicode: "f812", type: 'fas'},
	{ class: "laugh", unicode: "f599", type: 'fas'},
	{ class: "laugh-beam", unicode: "f59a", type: 'fas'},
	{ class: "laugh-squint", unicode: "f59b", type: 'fas'},
	{ class: "laugh-wink", unicode: "f59c", type: 'fas'},
	{ class: "layer-group", unicode: "f5fd", type: 'fas'},
	{ class: "leaf", unicode: "f06c", type: 'fas'},
	{ class: "lemon", unicode: "f094", type: 'fas'},
	{ class: "less-than", unicode: "f536", type: 'fas'},
	{ class: "less-than-equal", unicode: "f537", type: 'fas'},
	{ class: "level-down-alt", unicode: "f3be", type: 'fas'},
	{ class: "level-up-alt", unicode: "f3bf", type: 'fas'},
	{ class: "life-ring", unicode: "f1cd", type: 'fas'},
	{ class: "lightbulb", unicode: "f0eb", type: 'fas'},
	{ class: "link", unicode: "f0c1", type: 'fas'},
	{ class: "lira-sign", unicode: "f195", type: 'fas'},
	{ class: "list", unicode: "f03a", type: 'fas'},
	{ class: "list-alt", unicode: "f022", type: 'fas'},
	{ class: "list-ol", unicode: "f0cb", type: 'fas'},
	{ class: "list-ul", unicode: "f0ca", type: 'fas'},
	{ class: "location-arrow", unicode: "f124", type: 'fas'},
	{ class: "lock", unicode: "f023", type: 'fas'},
	{ class: "lock-open", unicode: "f3c1", type: 'fas'},
	{ class: "long-arrow-alt-down", unicode: "f309", type: 'fas'},
	{ class: "long-arrow-alt-left", unicode: "f30a", type: 'fas'},
	{ class: "long-arrow-alt-right", unicode: "f30b", type: 'fas'},
	{ class: "long-arrow-alt-up", unicode: "f30c", type: 'fas'},
	{ class: "low-vision", unicode: "f2a8", type: 'fas'},
	{ class: "luggage-cart", unicode: "f59d", type: 'fas'},
	{ class: "magic", unicode: "f0d0", type: 'fas'},
	{ class: "magnet", unicode: "f076", type: 'fas'},
	{ class: "mail-bulk", unicode: "f674", type: 'fas'},
	{ class: "male", unicode: "f183", type: 'fas'},
	{ class: "map", unicode: "f279", type: 'fas'},
	{ class: "map-marked", unicode: "f59f", type: 'fas'},
	{ class: "map-marked-alt", unicode: "f5a0", type: 'fas'},
	{ class: "map-marker", unicode: "f041", type: 'fas'},
	{ class: "map-marker-alt", unicode: "f3c5", type: 'fas'},
	{ class: "map-pin", unicode: "f276", type: 'fas'},
	{ class: "map-signs", unicode: "f277", type: 'fas'},
	{ class: "marker", unicode: "f5a1", type: 'fas'},
	{ class: "mars", unicode: "f222", type: 'fas'},
	{ class: "mars-double", unicode: "f227", type: 'fas'},
	{ class: "mars-stroke", unicode: "f229", type: 'fas'},
	{ class: "mars-stroke-h", unicode: "f22b", type: 'fas'},
	{ class: "mars-stroke-v", unicode: "f22a", type: 'fas'},
	{ class: "mask", unicode: "f6fa", type: 'fas'},
	{ class: "medal", unicode: "f5a2", type: 'fas'},
	{ class: "medkit", unicode: "f0fa", type: 'fas'},
	{ class: "meh", unicode: "f11a", type: 'fas'},
	{ class: "meh-blank", unicode: "f5a4", type: 'fas'},
	{ class: "meh-rolling-eyes", unicode: "f5a5", type: 'fas'},
	{ class: "memory", unicode: "f538", type: 'fas'},
	{ class: "menorah", unicode: "f676", type: 'fas'},
	{ class: "mercury", unicode: "f223", type: 'fas'},
	{ class: "meteor", unicode: "f753", type: 'fas'},
	{ class: "microchip", unicode: "f2db", type: 'fas'},
	{ class: "microphone", unicode: "f130", type: 'fas'},
	{ class: "microphone-alt", unicode: "f3c9", type: 'fas'},
	{ class: "microphone-alt-slash", unicode: "f539", type: 'fas'},
	{ class: "microphone-slash", unicode: "f131", type: 'fas'},
	{ class: "microscope", unicode: "f610", type: 'fas'},
	{ class: "minus", unicode: "f068", type: 'fas'},
	{ class: "minus-circle", unicode: "f056", type: 'fas'},
	{ class: "minus-square", unicode: "f146", type: 'fas'},
	{ class: "mitten", unicode: "f7b5", type: 'fas'},
	{ class: "mobile", unicode: "f10b", type: 'fas'},
	{ class: "mobile-alt", unicode: "f3cd", type: 'fas'},
	{ class: "money-bill", unicode: "f0d6", type: 'fas'},
	{ class: "money-bill-alt", unicode: "f3d1", type: 'fas'},
	{ class: "money-bill-wave", unicode: "f53a", type: 'fas'},
	{ class: "money-bill-wave-alt", unicode: "f53b", type: 'fas'},
	{ class: "money-check", unicode: "f53c", type: 'fas'},
	{ class: "money-check-alt", unicode: "f53d", type: 'fas'},
	{ class: "monument", unicode: "f5a6", type: 'fas'},
	{ class: "moon", unicode: "f186", type: 'fas'},
	{ class: "mortar-pestle", unicode: "f5a7", type: 'fas'},
	{ class: "mosque", unicode: "f678", type: 'fas'},
	{ class: "motorcycle", unicode: "f21c", type: 'fas'},
	{ class: "mountain", unicode: "f6fc", type: 'fas'},
	{ class: "mouse-pointer", unicode: "f245", type: 'fas'},
	{ class: "mug-hot", unicode: "f7b6", type: 'fas'},
	{ class: "music", unicode: "f001", type: 'fas'},
	{ class: "network-wired", unicode: "f6ff", type: 'fas'},
	{ class: "neuter", unicode: "f22c", type: 'fas'},
	{ class: "newspaper", unicode: "f1ea", type: 'fas'},
	{ class: "not-equal", unicode: "f53e", type: 'fas'},
	{ class: "notes-medical", unicode: "f481", type: 'fas'},
	{ class: "object-group", unicode: "f247", type: 'fas'},
	{ class: "object-ungroup", unicode: "f248", type: 'fas'},
	{ class: "oil-can", unicode: "f613", type: 'fas'},
	{ class: "om", unicode: "f679", type: 'fas'},
	{ class: "otter", unicode: "f700", type: 'fas'},
	{ class: "outdent", unicode: "f03b", type: 'fas'},
	{ class: "pager", unicode: "f815", type: 'fas'},
	{ class: "paint-brush", unicode: "f1fc", type: 'fas'},
	{ class: "paint-roller", unicode: "f5aa", type: 'fas'},
	{ class: "palette", unicode: "f53f", type: 'fas'},
	{ class: "pallet", unicode: "f482", type: 'fas'},
	{ class: "paper-plane", unicode: "f1d8", type: 'fas'},
	{ class: "paperclip", unicode: "f0c6", type: 'fas'},
	{ class: "parachute-box", unicode: "f4cd", type: 'fas'},
	{ class: "paragraph", unicode: "f1dd", type: 'fas'},
	{ class: "parking", unicode: "f540", type: 'fas'},
	{ class: "passport", unicode: "f5ab", type: 'fas'},
	{ class: "pastafarianism", unicode: "f67b", type: 'fas'},
	{ class: "paste", unicode: "f0ea", type: 'fas'},
	{ class: "pause", unicode: "f04c", type: 'fas'},
	{ class: "pause-circle", unicode: "f28b", type: 'fas'},
	{ class: "paw", unicode: "f1b0", type: 'fas'},
	{ class: "peace", unicode: "f67c", type: 'fas'},
	{ class: "pen", unicode: "f304", type: 'fas'},
	{ class: "pen-alt", unicode: "f305", type: 'fas'},
	{ class: "pen-fancy", unicode: "f5ac", type: 'fas'},
	{ class: "pen-nib", unicode: "f5ad", type: 'fas'},
	{ class: "pen-square", unicode: "f14b", type: 'fas'},
	{ class: "pencil-alt", unicode: "f303", type: 'fas'},
	{ class: "pencil-ruler", unicode: "f5ae", type: 'fas'},
	{ class: "people-carry", unicode: "f4ce", type: 'fas'},
	{ class: "pepper-hot", unicode: "f816", type: 'fas'},
	{ class: "percent", unicode: "f295", type: 'fas'},
	{ class: "percentage", unicode: "f541", type: 'fas'},
	{ class: "person-booth", unicode: "f756", type: 'fas'},
	{ class: "phone", unicode: "f095", type: 'fas'},
	{ class: "phone-slash", unicode: "f3dd", type: 'fas'},
	{ class: "phone-square", unicode: "f098", type: 'fas'},
	{ class: "phone-volume", unicode: "f2a0", type: 'fas'},
	{ class: "piggy-bank", unicode: "f4d3", type: 'fas'},
	{ class: "pills", unicode: "f484", type: 'fas'},
	{ class: "pizza-slice", unicode: "f818", type: 'fas'},
	{ class: "place-of-worship", unicode: "f67f", type: 'fas'},
	{ class: "plane", unicode: "f072", type: 'fas'},
	{ class: "plane-arrival", unicode: "f5af", type: 'fas'},
	{ class: "plane-departure", unicode: "f5b0", type: 'fas'},
	{ class: "play", unicode: "f04b", type: 'fas'},
	{ class: "play-circle", unicode: "f144", type: 'fas'},
	{ class: "plug", unicode: "f1e6", type: 'fas'},
	{ class: "plus", unicode: "f067", type: 'fas'},
	{ class: "plus-circle", unicode: "f055", type: 'fas'},
	{ class: "plus-square", unicode: "f0fe", type: 'fas'},
	{ class: "podcast", unicode: "f2ce", type: 'fas'},
	{ class: "poll", unicode: "f681", type: 'fas'},
	{ class: "poll-h", unicode: "f682", type: 'fas'},
	{ class: "poo", unicode: "f2fe", type: 'fas'},
	{ class: "poo-storm", unicode: "f75a", type: 'fas'},
	{ class: "poop", unicode: "f619", type: 'fas'},
	{ class: "portrait", unicode: "f3e0", type: 'fas'},
	{ class: "pound-sign", unicode: "f154", type: 'fas'},
	{ class: "power-off", unicode: "f011", type: 'fas'},
	{ class: "pray", unicode: "f683", type: 'fas'},
	{ class: "praying-hands", unicode: "f684", type: 'fas'},
	{ class: "prescription", unicode: "f5b1", type: 'fas'},
	{ class: "prescription-bottle", unicode: "f485", type: 'fas'},
	{ class: "prescription-bottle-alt", unicode: "f486", type: 'fas'},
	{ class: "print", unicode: "f02f", type: 'fas'},
	{ class: "procedures", unicode: "f487", type: 'fas'},
	{ class: "project-diagram", unicode: "f542", type: 'fas'},
	{ class: "puzzle-piece", unicode: "f12e", type: 'fas'},
	{ class: "qrcode", unicode: "f029", type: 'fas'},
	{ class: "question", unicode: "f128", type: 'fas'},
	{ class: "question-circle", unicode: "f059", type: 'fas'},
	{ class: "quidditch", unicode: "f458", type: 'fas'},
	{ class: "quote-left", unicode: "f10d", type: 'fas'},
	{ class: "quote-right", unicode: "f10e", type: 'fas'},
	{ class: "quran", unicode: "f687", type: 'fas'},
	{ class: "radiation", unicode: "f7b9", type: 'fas'},
	{ class: "radiation-alt", unicode: "f7ba", type: 'fas'},
	{ class: "rainbow", unicode: "f75b", type: 'fas'},
	{ class: "random", unicode: "f074", type: 'fas'},
	{ class: "receipt", unicode: "f543", type: 'fas'},
	{ class: "recycle", unicode: "f1b8", type: 'fas'},
	{ class: "redo", unicode: "f01e", type: 'fas'},
	{ class: "redo-alt", unicode: "f2f9", type: 'fas'},
	{ class: "registered", unicode: "f25d", type: 'fas'},
	{ class: "reply", unicode: "f3e5", type: 'fas'},
	{ class: "reply-all", unicode: "f122", type: 'fas'},
	{ class: "republican", unicode: "f75e", type: 'fas'},
	{ class: "restroom", unicode: "f7bd", type: 'fas'},
	{ class: "retweet", unicode: "f079", type: 'fas'},
	{ class: "ribbon", unicode: "f4d6", type: 'fas'},
	{ class: "ring", unicode: "f70b", type: 'fas'},
	{ class: "road", unicode: "f018", type: 'fas'},
	{ class: "robot", unicode: "f544", type: 'fas'},
	{ class: "rocket", unicode: "f135", type: 'fas'},
	{ class: "route", unicode: "f4d7", type: 'fas'},
	{ class: "rss", unicode: "f09e", type: 'fas'},
	{ class: "rss-square", unicode: "f143", type: 'fas'},
	{ class: "ruble-sign", unicode: "f158", type: 'fas'},
	{ class: "ruler", unicode: "f545", type: 'fas'},
	{ class: "ruler-combined", unicode: "f546", type: 'fas'},
	{ class: "ruler-horizontal", unicode: "f547", type: 'fas'},
	{ class: "ruler-vertical", unicode: "f548", type: 'fas'},
	{ class: "running", unicode: "f70c", type: 'fas'},
	{ class: "rupee-sign", unicode: "f156", type: 'fas'},
	{ class: "sad-cry", unicode: "f5b3", type: 'fas'},
	{ class: "sad-tear", unicode: "f5b4", type: 'fas'},
	{ class: "satellite", unicode: "f7bf", type: 'fas'},
	{ class: "satellite-dish", unicode: "f7c0", type: 'fas'},
	{ class: "save", unicode: "f0c7", type: 'fas'},
	{ class: "school", unicode: "f549", type: 'fas'},
	{ class: "screwdriver", unicode: "f54a", type: 'fas'},
	{ class: "scroll", unicode: "f70e", type: 'fas'},
	{ class: "sd-card", unicode: "f7c2", type: 'fas'},
	{ class: "search", unicode: "f002", type: 'fas'},
	{ class: "search-dollar", unicode: "f688", type: 'fas'},
	{ class: "search-location", unicode: "f689", type: 'fas'},
	{ class: "search-minus", unicode: "f010", type: 'fas'},
	{ class: "search-plus", unicode: "f00e", type: 'fas'},
	{ class: "seedling", unicode: "f4d8", type: 'fas'},
	{ class: "server", unicode: "f233", type: 'fas'},
	{ class: "shapes", unicode: "f61f", type: 'fas'},
	{ class: "share", unicode: "f064", type: 'fas'},
	{ class: "share-alt", unicode: "f1e0", type: 'fas'},
	{ class: "share-alt-square", unicode: "f1e1", type: 'fas'},
	{ class: "share-square", unicode: "f14d", type: 'fas'},
	{ class: "shekel-sign", unicode: "f20b", type: 'fas'},
	{ class: "shield-alt", unicode: "f3ed", type: 'fas'},
	{ class: "ship", unicode: "f21a", type: 'fas'},
	{ class: "shipping-fast", unicode: "f48b", type: 'fas'},
	{ class: "shoe-prints", unicode: "f54b", type: 'fas'},
	{ class: "shopping-bag", unicode: "f290", type: 'fas'},
	{ class: "shopping-basket", unicode: "f291", type: 'fas'},
	{ class: "shopping-cart", unicode: "f07a", type: 'fas'},
	{ class: "shower", unicode: "f2cc", type: 'fas'},
	{ class: "shuttle-van", unicode: "f5b6", type: 'fas'},
	{ class: "sign", unicode: "f4d9", type: 'fas'},
	{ class: "sign-in-alt", unicode: "f2f6", type: 'fas'},
	{ class: "sign-language", unicode: "f2a7", type: 'fas'},
	{ class: "sign-out-alt", unicode: "f2f5", type: 'fas'},
	{ class: "signal", unicode: "f012", type: 'fas'},
	{ class: "signature", unicode: "f5b7", type: 'fas'},
	{ class: "sim-card", unicode: "f7c4", type: 'fas'},
	{ class: "sitemap", unicode: "f0e8", type: 'fas'},
	{ class: "skating", unicode: "f7c5", type: 'fas'},
	{ class: "skiing", unicode: "f7c9", type: 'fas'},
	{ class: "skiing-nordic", unicode: "f7ca", type: 'fas'},
	{ class: "skull", unicode: "f54c", type: 'fas'},
	{ class: "skull-crossbones", unicode: "f714", type: 'fas'},
	{ class: "slash", unicode: "f715", type: 'fas'},
	{ class: "sleigh", unicode: "f7cc", type: 'fas'},
	{ class: "sliders-h", unicode: "f1de", type: 'fas'},
	{ class: "smile", unicode: "f118", type: 'fas'},
	{ class: "smile-beam", unicode: "f5b8", type: 'fas'},
	{ class: "smile-wink", unicode: "f4da", type: 'fas'},
	{ class: "smog", unicode: "f75f", type: 'fas'},
	{ class: "smoking", unicode: "f48d", type: 'fas'},
	{ class: "smoking-ban", unicode: "f54d", type: 'fas'},
	{ class: "sms", unicode: "f7cd", type: 'fas'},
	{ class: "snowboarding", unicode: "f7ce", type: 'fas'},
	{ class: "snowflake", unicode: "f2dc", type: 'fas'},
	{ class: "snowman", unicode: "f7d0", type: 'fas'},
	{ class: "snowplow", unicode: "f7d2", type: 'fas'},
	{ class: "socks", unicode: "f696", type: 'fas'},
	{ class: "solar-panel", unicode: "f5ba", type: 'fas'},
	{ class: "sort", unicode: "f0dc", type: 'fas'},
	{ class: "sort-alpha-down", unicode: "f15d", type: 'fas'},
	{ class: "sort-alpha-up", unicode: "f15e", type: 'fas'},
	{ class: "sort-amount-down", unicode: "f160", type: 'fas'},
	{ class: "sort-amount-up", unicode: "f161", type: 'fas'},
	{ class: "sort-down", unicode: "f0dd", type: 'fas'},
	{ class: "sort-numeric-down", unicode: "f162", type: 'fas'},
	{ class: "sort-numeric-up", unicode: "f163", type: 'fas'},
	{ class: "sort-up", unicode: "f0de", type: 'fas'},
	{ class: "spa", unicode: "f5bb", type: 'fas'},
	{ class: "space-shuttle", unicode: "f197", type: 'fas'},
	{ class: "spider", unicode: "f717", type: 'fas'},
	{ class: "spinner", unicode: "f110", type: 'fas'},
	{ class: "splotch", unicode: "f5bc", type: 'fas'},
	{ class: "spray-can", unicode: "f5bd", type: 'fas'},
	{ class: "square", unicode: "f0c8", type: 'fas'},
	{ class: "square-full", unicode: "f45c", type: 'fas'},
	{ class: "square-root-alt", unicode: "f698", type: 'fas'},
	{ class: "stamp", unicode: "f5bf", type: 'fas'},
	{ class: "star", unicode: "f005", type: 'fas'},
	{ class: "star-and-crescent", unicode: "f699", type: 'fas'},
	{ class: "star-half", unicode: "f089", type: 'fas'},
	{ class: "star-half-alt", unicode: "f5c0", type: 'fas'},
	{ class: "star-of-david", unicode: "f69a", type: 'fas'},
	{ class: "star-of-life", unicode: "f621", type: 'fas'},
	{ class: "step-backward", unicode: "f048", type: 'fas'},
	{ class: "step-forward", unicode: "f051", type: 'fas'},
	{ class: "stethoscope", unicode: "f0f1", type: 'fas'},
	{ class: "sticky-note", unicode: "f249", type: 'fas'},
	{ class: "stop", unicode: "f04d", type: 'fas'},
	{ class: "stop-circle", unicode: "f28d", type: 'fas'},
	{ class: "stopwatch", unicode: "f2f2", type: 'fas'},
	{ class: "store", unicode: "f54e", type: 'fas'},
	{ class: "store-alt", unicode: "f54f", type: 'fas'},
	{ class: "stream", unicode: "f550", type: 'fas'},
	{ class: "street-view", unicode: "f21d", type: 'fas'},
	{ class: "strikethrough", unicode: "f0cc", type: 'fas'},
	{ class: "stroopwafel", unicode: "f551", type: 'fas'},
	{ class: "subscript", unicode: "f12c", type: 'fas'},
	{ class: "subway", unicode: "f239", type: 'fas'},
	{ class: "suitcase", unicode: "f0f2", type: 'fas'},
	{ class: "suitcase-rolling", unicode: "f5c1", type: 'fas'},
	{ class: "sun", unicode: "f185", type: 'fas'},
	{ class: "superscript", unicode: "f12b", type: 'fas'},
	{ class: "surprise", unicode: "f5c2", type: 'fas'},
	{ class: "swatchbook", unicode: "f5c3", type: 'fas'},
	{ class: "swimmer", unicode: "f5c4", type: 'fas'},
	{ class: "swimming-pool", unicode: "f5c5", type: 'fas'},
	{ class: "synagogue", unicode: "f69b", type: 'fas'},
	{ class: "sync", unicode: "f021", type: 'fas'},
	{ class: "sync-alt", unicode: "f2f1", type: 'fas'},
	{ class: "syringe", unicode: "f48e", type: 'fas'},
	{ class: "table", unicode: "f0ce", type: 'fas'},
	{ class: "table-tennis", unicode: "f45d", type: 'fas'},
	{ class: "tablet", unicode: "f10a", type: 'fas'},
	{ class: "tablet-alt", unicode: "f3fa", type: 'fas'},
	{ class: "tablets", unicode: "f490", type: 'fas'},
	{ class: "tachometer-alt", unicode: "f3fd", type: 'fas'},
	{ class: "tag", unicode: "f02b", type: 'fas'},
	{ class: "tags", unicode: "f02c", type: 'fas'},
	{ class: "tape", unicode: "f4db", type: 'fas'},
	{ class: "tasks", unicode: "f0ae", type: 'fas'},
	{ class: "taxi", unicode: "f1ba", type: 'fas'},
	{ class: "teeth", unicode: "f62e", type: 'fas'},
	{ class: "teeth-open", unicode: "f62f", type: 'fas'},
	{ class: "temperature-high", unicode: "f769", type: 'fas'},
	{ class: "temperature-low", unicode: "f76b", type: 'fas'},
	{ class: "tenge", unicode: "f7d7", type: 'fas'},
	{ class: "terminal", unicode: "f120", type: 'fas'},
	{ class: "text-height", unicode: "f034", type: 'fas'},
	{ class: "text-width", unicode: "f035", type: 'fas'},
	{ class: "th", unicode: "f00a", type: 'fas'},
	{ class: "th-large", unicode: "f009", type: 'fas'},
	{ class: "th-list", unicode: "f00b", type: 'fas'},
	{ class: "theater-masks", unicode: "f630", type: 'fas'},
	{ class: "thermometer", unicode: "f491", type: 'fas'},
	{ class: "thermometer-empty", unicode: "f2cb", type: 'fas'},
	{ class: "thermometer-full", unicode: "f2c7", type: 'fas'},
	{ class: "thermometer-half", unicode: "f2c9", type: 'fas'},
	{ class: "thermometer-quarter", unicode: "f2ca", type: 'fas'},
	{ class: "thermometer-three-quarters", unicode: "f2c8", type: 'fas'},
	{ class: "thumbs-down", unicode: "f165", type: 'fas'},
	{ class: "thumbs-up", unicode: "f164", type: 'fas'},
	{ class: "thumbtack", unicode: "f08d", type: 'fas'},
	{ class: "ticket-alt", unicode: "f3ff", type: 'fas'},
	{ class: "times", unicode: "f00d", type: 'fas'},
	{ class: "times-circle", unicode: "f057", type: 'fas'},
	{ class: "tint", unicode: "f043", type: 'fas'},
	{ class: "tint-slash", unicode: "f5c7", type: 'fas'},
	{ class: "tired", unicode: "f5c8", type: 'fas'},
	{ class: "toggle-off", unicode: "f204", type: 'fas'},
	{ class: "toggle-on", unicode: "f205", type: 'fas'},
	{ class: "toilet", unicode: "f7d8", type: 'fas'},
	{ class: "toilet-paper", unicode: "f71e", type: 'fas'},
	{ class: "toolbox", unicode: "f552", type: 'fas'},
	{ class: "tools", unicode: "f7d9", type: 'fas'},
	{ class: "tooth", unicode: "f5c9", type: 'fas'},
	{ class: "torah", unicode: "f6a0", type: 'fas'},
	{ class: "torii-gate", unicode: "f6a1", type: 'fas'},
	{ class: "tractor", unicode: "f722", type: 'fas'},
	{ class: "trademark", unicode: "f25c", type: 'fas'},
	{ class: "traffic-light", unicode: "f637", type: 'fas'},
	{ class: "train", unicode: "f238", type: 'fas'},
	{ class: "tram", unicode: "f7da", type: 'fas'},
	{ class: "transgender", unicode: "f224", type: 'fas'},
	{ class: "transgender-alt", unicode: "f225", type: 'fas'},
	{ class: "trash", unicode: "f1f8", type: 'fas'},
	{ class: "trash-alt", unicode: "f2ed", type: 'fas'},
	{ class: "trash-restore", unicode: "f829", type: 'fas'},
	{ class: "trash-restore-alt", unicode: "f82a", type: 'fas'},
	{ class: "tree", unicode: "f1bb", type: 'fas'},
	{ class: "trophy", unicode: "f091", type: 'fas'},
	{ class: "truck", unicode: "f0d1", type: 'fas'},
	{ class: "truck-loading", unicode: "f4de", type: 'fas'},
	{ class: "truck-monster", unicode: "f63b", type: 'fas'},
	{ class: "truck-moving", unicode: "f4df", type: 'fas'},
	{ class: "truck-pickup", unicode: "f63c", type: 'fas'},
	{ class: "tshirt", unicode: "f553", type: 'fas'},
	{ class: "tty", unicode: "f1e4", type: 'fas'},
	{ class: "tv", unicode: "f26c", type: 'fas'},
	{ class: "umbrella", unicode: "f0e9", type: 'fas'},
	{ class: "umbrella-beach", unicode: "f5ca", type: 'fas'},
	{ class: "underline", unicode: "f0cd", type: 'fas'},
	{ class: "undo", unicode: "f0e2", type: 'fas'},
	{ class: "undo-alt", unicode: "f2ea", type: 'fas'},
	{ class: "universal-access", unicode: "f29a", type: 'fas'},
	{ class: "university", unicode: "f19c", type: 'fas'},
	{ class: "unlink", unicode: "f127", type: 'fas'},
	{ class: "unlock", unicode: "f09c", type: 'fas'},
	{ class: "unlock-alt", unicode: "f13e", type: 'fas'},
	{ class: "upload", unicode: "f093", type: 'fas'},
	{ class: "user", unicode: "f007", type: 'fas'},
	{ class: "user-alt", unicode: "f406", type: 'fas'},
	{ class: "user-alt-slash", unicode: "f4fa", type: 'fas'},
	{ class: "user-astronaut", unicode: "f4fb", type: 'fas'},
	{ class: "user-check", unicode: "f4fc", type: 'fas'},
	{ class: "user-circle", unicode: "f2bd", type: 'fas'},
	{ class: "user-clock", unicode: "f4fd", type: 'fas'},
	{ class: "user-cog", unicode: "f4fe", type: 'fas'},
	{ class: "user-edit", unicode: "f4ff", type: 'fas'},
	{ class: "user-friends", unicode: "f500", type: 'fas'},
	{ class: "user-graduate", unicode: "f501", type: 'fas'},
	{ class: "user-injured", unicode: "f728", type: 'fas'},
	{ class: "user-lock", unicode: "f502", type: 'fas'},
	{ class: "user-md", unicode: "f0f0", type: 'fas'},
	{ class: "user-minus", unicode: "f503", type: 'fas'},
	{ class: "user-ninja", unicode: "f504", type: 'fas'},
	{ class: "user-nurse", unicode: "f82f", type: 'fas'},
	{ class: "user-plus", unicode: "f234", type: 'fas'},
	{ class: "user-secret", unicode: "f21b", type: 'fas'},
	{ class: "user-shield", unicode: "f505", type: 'fas'},
	{ class: "user-slash", unicode: "f506", type: 'fas'},
	{ class: "user-tag", unicode: "f507", type: 'fas'},
	{ class: "user-tie", unicode: "f508", type: 'fas'},
	{ class: "user-times", unicode: "f235", type: 'fas'},
	{ class: "users", unicode: "f0c0", type: 'fas'},
	{ class: "users-cog", unicode: "f509", type: 'fas'},
	{ class: "utensil-spoon", unicode: "f2e5", type: 'fas'},
	{ class: "utensils", unicode: "f2e7", type: 'fas'},
	{ class: "vector-square", unicode: "f5cb", type: 'fas'},
	{ class: "venus", unicode: "f221", type: 'fas'},
	{ class: "venus-double", unicode: "f226", type: 'fas'},
	{ class: "venus-mars", unicode: "f228", type: 'fas'},
	{ class: "vial", unicode: "f492", type: 'fas'},
	{ class: "vials", unicode: "f493", type: 'fas'},
	{ class: "video", unicode: "f03d", type: 'fas'},
	{ class: "video-slash", unicode: "f4e2", type: 'fas'},
	{ class: "vihara", unicode: "f6a7", type: 'fas'},
	{ class: "volleyball-ball", unicode: "f45f", type: 'fas'},
	{ class: "volume-down", unicode: "f027", type: 'fas'},
	{ class: "volume-mute", unicode: "f6a9", type: 'fas'},
	{ class: "volume-off", unicode: "f026", type: 'fas'},
	{ class: "volume-up", unicode: "f028", type: 'fas'},
	{ class: "vote-yea", unicode: "f772", type: 'fas'},
	{ class: "vr-cardboard", unicode: "f729", type: 'fas'},
	{ class: "walking", unicode: "f554", type: 'fas'},
	{ class: "wallet", unicode: "f555", type: 'fas'},
	{ class: "warehouse", unicode: "f494", type: 'fas'},
	{ class: "water", unicode: "f773", type: 'fas'},
	{ class: "wave-square", unicode: "f83e", type: 'fas'},
	{ class: "weight", unicode: "f496", type: 'fas'},
	{ class: "weight-hanging", unicode: "f5cd", type: 'fas'},
	{ class: "wheelchair", unicode: "f193", type: 'fas'},
	{ class: "wifi", unicode: "f1eb", type: 'fas'},
	{ class: "wind", unicode: "f72e", type: 'fas'},
	{ class: "window-close", unicode: "f410", type: 'fas'},
	{ class: "window-maximize", unicode: "f2d0", type: 'fas'},
	{ class: "window-minimize", unicode: "f2d1", type: 'fas'},
	{ class: "window-restore", unicode: "f2d2", type: 'fas'},
	{ class: "wine-bottle", unicode: "f72f", type: 'fas'},
	{ class: "wine-glass", unicode: "f4e3", type: 'fas'},
	{ class: "wine-glass-alt", unicode: "f5ce", type: 'fas'},
	{ class: "won-sign", unicode: "f159", type: 'fas'},
	{ class: "wrench", unicode: "f0ad", type: 'fas'},
	{ class: "x-ray", unicode: "f497", type: 'fas'},
	{ class: "yen-sign", unicode: "f157", type: 'fas'},
	{ class: "yin-yang", unicode: "f6ad", type: 'fas'    },
    {class: "500px", unicode: "f26e", type: "fab"},
    {class: "accessible-icon", unicode: "f368", type: "fab"},
    {class: "accusoft", unicode: "f369", type: "fab"},
    {class: "acquisitions-incorporated", unicode: "f6af", type: "fab"},
    {class: "adn", unicode: "f170", type: "fab"},
    {class: "adobe", unicode: "f778", type: "fab"},
    {class: "adversal", unicode: "f36a", type: "fab"},
    {class: "affiliatetheme", unicode: "f36b", type: "fab"},
    {class: "airbnb", unicode: "f834", type: "fab"},
    {class: "algolia", unicode: "f36c", type: "fab"},
    {class: "alipay", unicode: "f642", type: "fab"},
    {class: "amazon", unicode: "f270", type: "fab"},
    {class: "amazon-pay", unicode: "f42c", type: "fab"},
    {class: "amilia", unicode: "f36d", type: "fab"},
    {class: "android", unicode: "f17b", type: "fab"},
    {class: "angellist", unicode: "f209", type: "fab"},
    {class: "angrycreative", unicode: "f36e", type: "fab"},
    {class: "angular", unicode: "f420", type: "fab"},
    {class: "app-store", unicode: "f36f", type: "fab"},
    {class: "app-store-ios", unicode: "f370", type: "fab"},
    {class: "apper", unicode: "f371", type: "fab"},
    {class: "apple", unicode: "f179", type: "fab"},
    {class: "apple-pay", unicode: "f415", type: "fab"},
    {class: "artstation", unicode: "f77a", type: "fab"},
    {class: "asymmetrik", unicode: "f372", type: "fab"},
    {class: "atlassian", unicode: "f77b", type: "fab"},
    {class: "audible", unicode: "f373", type: "fab"},
    {class: "autoprefixer", unicode: "f41c", type: "fab"},
    {class: "avianex", unicode: "f374", type: "fab"},
    {class: "aviato", unicode: "f421", type: "fab"},
    {class: "aws", unicode: "f375", type: "fab"},
    {class: "bandcamp", unicode: "f2d5", type: "fab"},
    {class: "battle-net", unicode: "f835", type: "fab"},
    {class: "behance", unicode: "f1b4", type: "fab"},
    {class: "behance-square", unicode: "f1b5", type: "fab"},
    {class: "bimobject", unicode: "f378", type: "fab"},
    {class: "bitbucket", unicode: "f171", type: "fab"},
    {class: "bitcoin", unicode: "f379", type: "fab"},
    {class: "bity", unicode: "f37a", type: "fab"},
    {class: "black-tie", unicode: "f27e", type: "fab"},
    {class: "blackberry", unicode: "f37b", type: "fab"},
    {class: "blogger", unicode: "f37c", type: "fab"},
    {class: "blogger-b", unicode: "f37d", type: "fab"},
    {class: "bluetooth", unicode: "f293", type: "fab"},
    {class: "bluetooth-b", unicode: "f294", type: "fab"},
    {class: "bootstrap", unicode: "f836", type: "fab"},
    {class: "btc", unicode: "f15a", type: "fab"},
    {class: "buffer", unicode: "f837", type: "fab"},
    {class: "buromobelexperte", unicode: "f37f", type: "fab"},
    {class: "buysellads", unicode: "f20d", type: "fab"},
    {class: "canadian-maple-leaf", unicode: "f785", type: "fab"},
    {class: "cc-amazon-pay", unicode: "f42d", type: "fab"},
    {class: "cc-amex", unicode: "f1f3", type: "fab"},
    {class: "cc-apple-pay", unicode: "f416", type: "fab"},
    {class: "cc-diners-club", unicode: "f24c", type: "fab"},
    {class: "cc-discover", unicode: "f1f2", type: "fab"},
    {class: "cc-jcb", unicode: "f24b", type: "fab"},
    {class: "cc-mastercard", unicode: "f1f1", type: "fab"},
    {class: "cc-paypal", unicode: "f1f4", type: "fab"},
    {class: "cc-stripe", unicode: "f1f5", type: "fab"},
    {class: "cc-visa", unicode: "f1f0", type: "fab"},
    {class: "centercode", unicode: "f380", type: "fab"},
    {class: "centos", unicode: "f789", type: "fab"},
    {class: "chrome", unicode: "f268", type: "fab"},
    {class: "chromecast", unicode: "f838", type: "fab"},
    {class: "cloudscale", unicode: "f383", type: "fab"},
    {class: "cloudsmith", unicode: "f384", type: "fab"},
    {class: "cloudversify", unicode: "f385", type: "fab"},
    {class: "codepen", unicode: "f1cb", type: "fab"},
    {class: "codiepie", unicode: "f284", type: "fab"},
    {class: "confluence", unicode: "f78d", type: "fab"},
    {class: "connectdevelop", unicode: "f20e", type: "fab"},
    {class: "contao", unicode: "f26d", type: "fab"},
    {class: "cpanel", unicode: "f388", type: "fab"},
    {class: "creative-commons", unicode: "f25e", type: "fab"},
    {class: "creative-commons-by", unicode: "f4e7", type: "fab"},
    {class: "creative-commons-nc", unicode: "f4e8", type: "fab"},
    {class: "creative-commons-nc-eu", unicode: "f4e9", type: "fab"},
    {class: "creative-commons-nc-jp", unicode: "f4ea", type: "fab"},
    {class: "creative-commons-nd", unicode: "f4eb", type: "fab"},
    {class: "creative-commons-pd", unicode: "f4ec", type: "fab"},
    {class: "creative-commons-pd-alt", unicode: "f4ed", type: "fab"},
    {class: "creative-commons-remix", unicode: "f4ee", type: "fab"},
    {class: "creative-commons-sa", unicode: "f4ef", type: "fab"},
    {class: "creative-commons-sampling", unicode: "f4f0", type: "fab"},
    {class: "creative-commons-sampling-plus", unicode: "f4f1", type: "fab"},
    {class: "creative-commons-share", unicode: "f4f2", type: "fab"},
    {class: "creative-commons-zero", unicode: "f4f3", type: "fab"},
    {class: "critical-role", unicode: "f6c9", type: "fab"},
    {class: "css3", unicode: "f13c", type: "fab"},
    {class: "css3-alt", unicode: "f38b", type: "fab"},
    {class: "cuttlefish", unicode: "f38c", type: "fab"},
    {class: "d-and-d", unicode: "f38d", type: "fab"},
    {class: "d-and-d-beyond", unicode: "f6ca", type: "fab"},
    {class: "dashcube", unicode: "f210", type: "fab"},
    {class: "delicious", unicode: "f1a5", type: "fab"},
    {class: "deploydog", unicode: "f38e", type: "fab"},
    {class: "deskpro", unicode: "f38f", type: "fab"},
    {class: "dev", unicode: "f6cc", type: "fab"},
    {class: "deviantart", unicode: "f1bd", type: "fab"},
    {class: "dhl", unicode: "f790", type: "fab"},
    {class: "diaspora", unicode: "f791", type: "fab"},
    {class: "digg", unicode: "f1a6", type: "fab"},
    {class: "digital-ocean", unicode: "f391", type: "fab"},
    {class: "discord", unicode: "f392", type: "fab"},
    {class: "discourse", unicode: "f393", type: "fab"},
    {class: "dochub", unicode: "f394", type: "fab"},
    {class: "docker", unicode: "f395", type: "fab"},
    {class: "draft2digital", unicode: "f396", type: "fab"},
    {class: "dribbble", unicode: "f17d", type: "fab"},
    {class: "dribbble-square", unicode: "f397", type: "fab"},
    {class: "dropbox", unicode: "f16b", type: "fab"},
    {class: "drupal", unicode: "f1a9", type: "fab"},
    {class: "dyalog", unicode: "f399", type: "fab"},
    {class: "earlybirds", unicode: "f39a", type: "fab"},
    {class: "ebay", unicode: "f4f4", type: "fab"},
    {class: "edge", unicode: "f282", type: "fab"},
    {class: "elementor", unicode: "f430", type: "fab"},
    {class: "ello", unicode: "f5f1", type: "fab"},
    {class: "ember", unicode: "f423", type: "fab"},
    {class: "empire", unicode: "f1d1", type: "fab"},
    {class: "envira", unicode: "f299", type: "fab"},
    {class: "erlang", unicode: "f39d", type: "fab"},
    {class: "ethereum", unicode: "f42e", type: "fab"},
    {class: "etsy", unicode: "f2d7", type: "fab"},
    {class: "evernote", unicode: "f839", type: "fab"},
    {class: "expeditedssl", unicode: "f23e", type: "fab"},
    {class: "facebook", unicode: "f09a", type: "fab"},
    {class: "facebook-f", unicode: "f39e", type: "fab"},
    {class: "facebook-messenger", unicode: "f39f", type: "fab"},
    {class: "facebook-square", unicode: "f082", type: "fab"},
    {class: "fantasy-flight-games", unicode: "f6dc", type: "fab"},
    {class: "fedex", unicode: "f797", type: "fab"},
    {class: "fedora", unicode: "f798", type: "fab"},
    {class: "figma", unicode: "f799", type: "fab"},
    {class: "firefox", unicode: "f269", type: "fab"},
    {class: "first-order", unicode: "f2b0", type: "fab"},
    {class: "first-order-alt", unicode: "f50a", type: "fab"},
    {class: "firstdraft", unicode: "f3a1", type: "fab"},
    {class: "flickr", unicode: "f16e", type: "fab"},
    {class: "flipboard", unicode: "f44d", type: "fab"},
    {class: "fly", unicode: "f417", type: "fab"},
    {class: "font-awesome", unicode: "f2b4", type: "fab"},
    {class: "font-awesome-alt", unicode: "f35c", type: "fab"},
    {class: "font-awesome-flag", unicode: "f425", type: "fab"},
    {class: "fonticons", unicode: "f280", type: "fab"},
    {class: "fonticons-fi", unicode: "f3a2", type: "fab"},
    {class: "fort-awesome", unicode: "f286", type: "fab"},
    {class: "fort-awesome-alt", unicode: "f3a3", type: "fab"},
    {class: "forumbee", unicode: "f211", type: "fab"},
    {class: "foursquare", unicode: "f180", type: "fab"},
    {class: "free-code-camp", unicode: "f2c5", type: "fab"},
    {class: "freebsd", unicode: "f3a4", type: "fab"},
    {class: "fulcrum", unicode: "f50b", type: "fab"},
    {class: "galactic-republic", unicode: "f50c", type: "fab"},
    {class: "galactic-senate", unicode: "f50d", type: "fab"},
    {class: "get-pocket", unicode: "f265", type: "fab"},
    {class: "gg", unicode: "f260", type: "fab"},
    {class: "gg-circle", unicode: "f261", type: "fab"},
    {class: "git", unicode: "f1d3", type: "fab"},
    {class: "git-alt", unicode: "f841", type: "fab"},
    {class: "git-square", unicode: "f1d2", type: "fab"},
    {class: "github", unicode: "f09b", type: "fab"},
    {class: "github-alt", unicode: "f113", type: "fab"},
    {class: "github-square", unicode: "f092", type: "fab"},
    {class: "gitkraken", unicode: "f3a6", type: "fab"},
    {class: "gitlab", unicode: "f296", type: "fab"},
    {class: "gitter", unicode: "f426", type: "fab"},
    {class: "glide", unicode: "f2a5", type: "fab"},
    {class: "glide-g", unicode: "f2a6", type: "fab"},
    {class: "gofore", unicode: "f3a7", type: "fab"},
    {class: "goodreads", unicode: "f3a8", type: "fab"},
    {class: "goodreads-g", unicode: "f3a9", type: "fab"},
    {class: "google", unicode: "f1a0", type: "fab"},
    {class: "google-drive", unicode: "f3aa", type: "fab"},
    {class: "google-play", unicode: "f3ab", type: "fab"},
    {class: "google-plus", unicode: "f2b3", type: "fab"},
    {class: "google-plus-g", unicode: "f0d5", type: "fab"},
    {class: "google-plus-square", unicode: "f0d4", type: "fab"},
    {class: "google-wallet", unicode: "f1ee", type: "fab"},
    {class: "gratipay", unicode: "f184", type: "fab"},
    {class: "grav", unicode: "f2d6", type: "fab"},
    {class: "gripfire", unicode: "f3ac", type: "fab"},
    {class: "grunt", unicode: "f3ad", type: "fab"},
    {class: "gulp", unicode: "f3ae", type: "fab"},
    {class: "hacker-news", unicode: "f1d4", type: "fab"},
    {class: "hacker-news-square", unicode: "f3af", type: "fab"},
    {class: "hackerrank", unicode: "f5f7", type: "fab"},
    {class: "hips", unicode: "f452", type: "fab"},
    {class: "hire-a-helper", unicode: "f3b0", type: "fab"},
    {class: "hooli", unicode: "f427", type: "fab"},
    {class: "hornbill", unicode: "f592", type: "fab"},
    {class: "hotjar", unicode: "f3b1", type: "fab"},
    {class: "houzz", unicode: "f27c", type: "fab"},
    {class: "html5", unicode: "f13b", type: "fab"},
    {class: "hubspot", unicode: "f3b2", type: "fab"},
    {class: "imdb", unicode: "f2d8", type: "fab"},
    {class: "instagram", unicode: "f16d", type: "fab"},
    {class: "intercom", unicode: "f7af", type: "fab"},
    {class: "internet-explorer", unicode: "f26b", type: "fab"},
    {class: "invision", unicode: "f7b0", type: "fab"},
    {class: "ioxhost", unicode: "f208", type: "fab"},
    {class: "itch-io", unicode: "f83a", type: "fab"},
    {class: "itunes", unicode: "f3b4", type: "fab"},
    {class: "itunes-note", unicode: "f3b5", type: "fab"},
    {class: "java", unicode: "f4e4", type: "fab"},
    {class: "jedi-order", unicode: "f50e", type: "fab"},
    {class: "jenkins", unicode: "f3b6", type: "fab"},
    {class: "jira", unicode: "f7b1", type: "fab"},
    {class: "joget", unicode: "f3b7", type: "fab"},
    {class: "joomla", unicode: "f1aa", type: "fab"},
    {class: "js", unicode: "f3b8", type: "fab"},
    {class: "js-square", unicode: "f3b9", type: "fab"},
    {class: "jsfiddle", unicode: "f1cc", type: "fab"},
    {class: "kaggle", unicode: "f5fa", type: "fab"},
    {class: "keybase", unicode: "f4f5", type: "fab"},
    {class: "keycdn", unicode: "f3ba", type: "fab"},
    {class: "kickstarter", unicode: "f3bb", type: "fab"},
    {class: "kickstarter-k", unicode: "f3bc", type: "fab"},
    {class: "korvue", unicode: "f42f", type: "fab"},
    {class: "laravel", unicode: "f3bd", type: "fab"},
    {class: "lastfm", unicode: "f202", type: "fab"},
    {class: "lastfm-square", unicode: "f203", type: "fab"},
    {class: "leanpub", unicode: "f212", type: "fab"},
    {class: "less", unicode: "f41d", type: "fab"},
    {class: "line", unicode: "f3c0", type: "fab"},
    {class: "linkedin", unicode: "f08c", type: "fab"},
    {class: "linkedin-in", unicode: "f0e1", type: "fab"},
    {class: "linode", unicode: "f2b8", type: "fab"},
    {class: "linux", unicode: "f17c", type: "fab"},
    {class: "lyft", unicode: "f3c3", type: "fab"},
    {class: "magento", unicode: "f3c4", type: "fab"},
    {class: "mailchimp", unicode: "f59e", type: "fab"},
    {class: "mandalorian", unicode: "f50f", type: "fab"},
    {class: "markdown", unicode: "f60f", type: "fab"},
    {class: "mastodon", unicode: "f4f6", type: "fab"},
    {class: "maxcdn", unicode: "f136", type: "fab"},
    {class: "medapps", unicode: "f3c6", type: "fab"},
    {class: "medium", unicode: "f23a", type: "fab"},
    {class: "medium-m", unicode: "f3c7", type: "fab"},
    {class: "medrt", unicode: "f3c8", type: "fab"},
    {class: "meetup", unicode: "f2e0", type: "fab"},
    {class: "megaport", unicode: "f5a3", type: "fab"},
    {class: "mendeley", unicode: "f7b3", type: "fab"},
    {class: "microsoft", unicode: "f3ca", type: "fab"},
    {class: "mix", unicode: "f3cb", type: "fab"},
    {class: "mixcloud", unicode: "f289", type: "fab"},
    {class: "mizuni", unicode: "f3cc", type: "fab"},
    {class: "modx", unicode: "f285", type: "fab"},
    {class: "monero", unicode: "f3d0", type: "fab"},
    {class: "napster", unicode: "f3d2", type: "fab"},
    {class: "neos", unicode: "f612", type: "fab"},
    {class: "nimblr", unicode: "f5a8", type: "fab"},
    {class: "node", unicode: "f419", type: "fab"},
    {class: "node-js", unicode: "f3d3", type: "fab"},
    {class: "npm", unicode: "f3d4", type: "fab"},
    {class: "ns8", unicode: "f3d5", type: "fab"},
    {class: "nutritionix", unicode: "f3d6", type: "fab"},
    {class: "odnoklassniki", unicode: "f263", type: "fab"},
    {class: "odnoklassniki-square", unicode: "f264", type: "fab"},
    {class: "old-republic", unicode: "f510", type: "fab"},
    {class: "opencart", unicode: "f23d", type: "fab"},
    {class: "openid", unicode: "f19b", type: "fab"},
    {class: "opera", unicode: "f26a", type: "fab"},
    {class: "optin-monster", unicode: "f23c", type: "fab"},
    {class: "osi", unicode: "f41a", type: "fab"},
    {class: "page4", unicode: "f3d7", type: "fab"},
    {class: "pagelines", unicode: "f18c", type: "fab"},
    {class: "palfed", unicode: "f3d8", type: "fab"},
    {class: "patreon", unicode: "f3d9", type: "fab"},
    {class: "paypal", unicode: "f1ed", type: "fab"},
    {class: "penny-arcade", unicode: "f704", type: "fab"},
    {class: "periscope", unicode: "f3da", type: "fab"},
    {class: "phabricator", unicode: "f3db", type: "fab"},
    {class: "phoenix-framework", unicode: "f3dc", type: "fab"},
    {class: "phoenix-squadron", unicode: "f511", type: "fab"},
    {class: "php", unicode: "f457", type: "fab"},
    {class: "pied-piper", unicode: "f2ae", type: "fab"},
    {class: "pied-piper-alt", unicode: "f1a8", type: "fab"},
    {class: "pied-piper-hat", unicode: "f4e5", type: "fab"},
    {class: "pied-piper-pp", unicode: "f1a7", type: "fab"},
    {class: "pinterest", unicode: "f0d2", type: "fab"},
    {class: "pinterest-p", unicode: "f231", type: "fab"},
    {class: "pinterest-square", unicode: "f0d3", type: "fab"},
    {class: "playstation", unicode: "f3df", type: "fab"},
    {class: "product-hunt", unicode: "f288", type: "fab"},
    {class: "pushed", unicode: "f3e1", type: "fab"},
    {class: "python", unicode: "f3e2", type: "fab"},
    {class: "qq", unicode: "f1d6", type: "fab"},
    {class: "quinscape", unicode: "f459", type: "fab"},
    {class: "quora", unicode: "f2c4", type: "fab"},
    {class: "r-project", unicode: "f4f7", type: "fab"},
    {class: "raspberry-pi", unicode: "f7bb", type: "fab"},
    {class: "ravelry", unicode: "f2d9", type: "fab"},
    {class: "react", unicode: "f41b", type: "fab"},
    {class: "reacteurope", unicode: "f75d", type: "fab"},
    {class: "readme", unicode: "f4d5", type: "fab"},
    {class: "rebel", unicode: "f1d0", type: "fab"},
    {class: "red-river", unicode: "f3e3", type: "fab"},
    {class: "reddit", unicode: "f1a1", type: "fab"},
    {class: "reddit-alien", unicode: "f281", type: "fab"},
    {class: "reddit-square", unicode: "f1a2", type: "fab"},
    {class: "redhat", unicode: "f7bc", type: "fab"},
    {class: "renren", unicode: "f18b", type: "fab"},
    {class: "replyd", unicode: "f3e6", type: "fab"},
    {class: "researchgate", unicode: "f4f8", type: "fab"},
    {class: "resolving", unicode: "f3e7", type: "fab"},
    {class: "rev", unicode: "f5b2", type: "fab"},
    {class: "rocketchat", unicode: "f3e8", type: "fab"},
    {class: "rockrms", unicode: "f3e9", type: "fab"},
    {class: "safari", unicode: "f267", type: "fab"},
    {class: "salesforce", unicode: "f83b", type: "fab"},
    {class: "sass", unicode: "f41e", type: "fab"},
    {class: "schlix", unicode: "f3ea", type: "fab"},
    {class: "scribd", unicode: "f28a", type: "fab"},
    {class: "searchengin", unicode: "f3eb", type: "fab"},
    {class: "sellcast", unicode: "f2da", type: "fab"},
    {class: "sellsy", unicode: "f213", type: "fab"},
    {class: "servicestack", unicode: "f3ec", type: "fab"},
    {class: "shirtsinbulk", unicode: "f214", type: "fab"},
    {class: "shopware", unicode: "f5b5", type: "fab"},
    {class: "simplybuilt", unicode: "f215", type: "fab"},
    {class: "sistrix", unicode: "f3ee", type: "fab"},
    {class: "sith", unicode: "f512", type: "fab"},
    {class: "sketch", unicode: "f7c6", type: "fab"},
    {class: "skyatlas", unicode: "f216", type: "fab"},
    {class: "skype", unicode: "f17e", type: "fab"},
    {class: "slack", unicode: "f198", type: "fab"},
    {class: "slack-hash", unicode: "f3ef", type: "fab"},
    {class: "slideshare", unicode: "f1e7", type: "fab"},
    {class: "snapchat", unicode: "f2ab", type: "fab"},
    {class: "snapchat-ghost", unicode: "f2ac", type: "fab"},
    {class: "snapchat-square", unicode: "f2ad", type: "fab"},
    {class: "soundcloud", unicode: "f1be", type: "fab"},
    {class: "sourcetree", unicode: "f7d3", type: "fab"},
    {class: "speakap", unicode: "f3f3", type: "fab"},
    {class: "speaker-deck", unicode: "f83c", type: "fab"},
    {class: "spotify", unicode: "f1bc", type: "fab"},
    {class: "squarespace", unicode: "f5be", type: "fab"},
    {class: "stack-exchange", unicode: "f18d", type: "fab"},
    {class: "stack-overflow", unicode: "f16c", type: "fab"},
    {class: "stackpath", unicode: "f842", type: "fab"},
    {class: "staylinked", unicode: "f3f5", type: "fab"},
    {class: "steam", unicode: "f1b6", type: "fab"},
    {class: "steam-square", unicode: "f1b7", type: "fab"},
    {class: "steam-symbol", unicode: "f3f6", type: "fab"},
    {class: "sticker-mule", unicode: "f3f7", type: "fab"},
    {class: "strava", unicode: "f428", type: "fab"},
    {class: "stripe", unicode: "f429", type: "fab"},
    {class: "stripe-s", unicode: "f42a", type: "fab"},
    {class: "studiovinari", unicode: "f3f8", type: "fab"},
    {class: "stumbleupon", unicode: "f1a4", type: "fab"},
    {class: "stumbleupon-circle", unicode: "f1a3", type: "fab"},
    {class: "superpowers", unicode: "f2dd", type: "fab"},
    {class: "supple", unicode: "f3f9", type: "fab"},
    {class: "suse", unicode: "f7d6", type: "fab"},
    {class: "symfony", unicode: "f83d", type: "fab"},
    {class: "teamspeak", unicode: "f4f9", type: "fab"},
    {class: "telegram", unicode: "f2c6", type: "fab"},
    {class: "telegram-plane", unicode: "f3fe", type: "fab"},
    {class: "tencent-weibo", unicode: "f1d5", type: "fab"},
    {class: "the-red-yeti", unicode: "f69d", type: "fab"},
    {class: "themeco", unicode: "f5c6", type: "fab"},
    {class: "themeisle", unicode: "f2b2", type: "fab"},
    {class: "think-peaks", unicode: "f731", type: "fab"},
    {class: "trade-federation", unicode: "f513", type: "fab"},
    {class: "trello", unicode: "f181", type: "fab"},
    {class: "tripadvisor", unicode: "f262", type: "fab"},
    {class: "tumblr", unicode: "f173", type: "fab"},
    {class: "tumblr-square", unicode: "f174", type: "fab"},
    {class: "twitch", unicode: "f1e8", type: "fab"},
    {class: "twitter", unicode: "f099", type: "fab"},
    {class: "twitter-square", unicode: "f081", type: "fab"},
    {class: "typo3", unicode: "f42b", type: "fab"},
    {class: "uber", unicode: "f402", type: "fab"},
    {class: "ubuntu", unicode: "f7df", type: "fab"},
    {class: "uikit", unicode: "f403", type: "fab"},
    {class: "uniregistry", unicode: "f404", type: "fab"},
    {class: "untappd", unicode: "f405", type: "fab"},
    {class: "ups", unicode: "f7e0", type: "fab"},
    {class: "usb", unicode: "f287", type: "fab"},
    {class: "usps", unicode: "f7e1", type: "fab"},
    {class: "ussunnah", unicode: "f407", type: "fab"},
    {class: "vaadin", unicode: "f408", type: "fab"},
    {class: "viacoin", unicode: "f237", type: "fab"},
    {class: "viadeo", unicode: "f2a9", type: "fab"},
    {class: "viadeo-square", unicode: "f2aa", type: "fab"},
    {class: "viber", unicode: "f409", type: "fab"},
    {class: "vimeo", unicode: "f40a", type: "fab"},
    {class: "vimeo-square", unicode: "f194", type: "fab"},
    {class: "vimeo-v", unicode: "f27d", type: "fab"},
    {class: "vine", unicode: "f1ca", type: "fab"},
    {class: "vk", unicode: "f189", type: "fab"},
    {class: "vnv", unicode: "f40b", type: "fab"},
    {class: "vuejs", unicode: "f41f", type: "fab"},
    {class: "waze", unicode: "f83f", type: "fab"},
    {class: "weebly", unicode: "f5cc", type: "fab"},
    {class: "weibo", unicode: "f18a", type: "fab"},
    {class: "weixin", unicode: "f1d7", type: "fab"},
    {class: "whatsapp", unicode: "f232", type: "fab"},
    {class: "whatsapp-square", unicode: "f40c", type: "fab"},
    {class: "whmcs", unicode: "f40d", type: "fab"},
    {class: "wikipedia-w", unicode: "f266", type: "fab"},
    {class: "windows", unicode: "f17a", type: "fab"},
    {class: "wix", unicode: "f5cf", type: "fab"},
    {class: "wizards-of-the-coast", unicode: "f730", type: "fab"},
    {class: "wolf-pack-battalion", unicode: "f514", type: "fab"},
    {class: "wordpress", unicode: "f19a", type: "fab"},
    {class: "wordpress-simple", unicode: "f411", type: "fab"},
    {class: "wpbeginner", unicode: "f297", type: "fab"},
    {class: "wpexplorer", unicode: "f2de", type: "fab"},
    {class: "wpforms", unicode: "f298", type: "fab"},
    {class: "wpressr", unicode: "f3e4", type: "fab"},
    {class: "xbox", unicode: "f412", type: "fab"},
    {class: "xing", unicode: "f168", type: "fab"},
    {class: "xing-square", unicode: "f169", type: "fab"},
    {class: "y-combinator", unicode: "f23b", type: "fab"},
    {class: "yahoo", unicode: "f19e", type: "fab"},
    {class: "yammer", unicode: "f840", type: "fab"},
    {class: "yandex", unicode: "f413", type: "fab"},
    {class: "yandex-international", unicode: "f414", type: "fab"},
    {class: "yarn", unicode: "f7e3", type: "fab"},
    {class: "yelp", unicode: "f1e9", type: "fab"},
    {class: "yoast", unicode: "f2b1", type: "fab"},
    {class: "youtube", unicode: "f167", type: "fab"},
    {class: "youtube-square", unicode: "f431", type: "fab"},
    {class: "zhihu", unicode: "f63f", type: "fab"}
];
// const md = require('markdown-it');
// const fa = require('markdown-it-fontawesome');

// md().use(fa);

export function activate(context: vscode.ExtensionContext) {
	let currentPanel: vscode.WebviewPanel | undefined = undefined;
	let webview = vscode.commands.registerCommand('extension.openNav', () => {
		currentPanel = vscode.window.createWebviewPanel(
			'nearest-icons-from-font-awesome', 
			'Nearest Icons',
			vscode.ViewColumn.One, 
			{
				enableScripts: true,
				localResourceRoots: [vscode.Uri.file(path.join(context.extensionPath, 'media'))]
			}
		);

		let scriptPath = vscode.Uri.file(path.join(context.extensionPath, 'media', 'main.js'));
		let jsSource = scriptPath.with({scheme: 'vscode-resource'});
		
		currentPanel.webview.html = getWebViewContent(jsSource);
		
		currentPanel.webview.onDidReceiveMessage(
			async message => {
				if (message.openIconPage) {
					vscode.env.openExternal(vscode.Uri.parse(message.openIconPage)).then((result) => {
						if (result) {
							console.log('Opening external success');
						} else {
							console.log('Opening external FAILED');
						}
					});
				}
			}
		);
	});

	let htmlCompletion = vscode.languages.registerCompletionItemProvider(
		[
			{
				scheme: 'file',
				language: 'html'
			},
			'plaintext'
		], 
		{
			provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext) {
				let completions = new vscode.CompletionList();

				faIcons.forEach(element => {
					let simple = new vscode.CompletionItem(`fa-${element.class}`);
						simple.insertText = new vscode.SnippetString(`<i class="${element.type} fa-${element.class}"></i>`);
						simple.detail = (element.type === 'fas' ? 'Solid' : 'Brand') + ' icon';
						simple.documentation = new vscode.MarkdownString(`**${element.class}** :fa-google:`);
					
					completions.items.push(simple);
				});				

				return completions;
			}
		}
	);

	let jsCompletion = vscode.languages.registerCompletionItemProvider(
		{
			scheme: 'file',
			language: 'javascript'
		}, 
		{
			provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext) {
				let completions = new vscode.CompletionList();

				faIcons.forEach(element => {
					let simple = new vscode.CompletionItem(`fa-${element.class}`);
						simple.insertText = new vscode.SnippetString(`'${element.type} fa-${element.class}'`);
						simple.detail = (element.type === 'fas' ? 'Solid' : 'Brand') + ' icon';
						simple.documentation = new vscode.MarkdownString(`**${element.class}**`);
					
					completions.items.push(simple);
				});				

				return completions;
			}
		}
	);

	let cssCompletion = vscode.languages.registerCompletionItemProvider(
		{
			scheme: 'file',
			language: 'css'
		}, 
		{
			provideCompletionItems(document: vscode.TextDocument, position: vscode.Position, token: vscode.CancellationToken, context: vscode.CompletionContext) {
				let completions = new vscode.CompletionList();

				faIcons.forEach(element => {
					let simple = new vscode.CompletionItem(`fa-${element.class}`);
						simple.insertText = new vscode.SnippetString(`content: '\\${element.unicode}';\nfont-weight: bold;\nfont-family: Font Awesome\\ 5 Free;`);
						simple.detail = (element.type === 'fas' ? 'Solid' : 'Brand') + ' icon';
						simple.documentation = new vscode.MarkdownString(`**${element.class}**`);
					
					completions.items.push(simple);
				});				

				return completions;
			}
		}
	);

	context.subscriptions.push(webview, htmlCompletion, jsCompletion, cssCompletion);
}

export function deactivate() {}

let nonce = getNonce();

function getWebViewContent(sourceJs: object) {
	return `
		<!DOCTYPE html>
		<html lang="en">
			<head>	
				<meta charset="UTF-8">
				<meta http-equiv="Content-Security-Policy" content="default-src 'self' https://use.fontawesome.com; img-src vscode-resource: https:; script-src 'nonce-${nonce}'; style-src 'self' https://use.fontawesome.com">
				<meta name="viewport" content="width=device-width, initial-scale=1.0">
				<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
				<title>Nearest Icons from Font-Awesome</title>
			</head>
			<body>
				<main></main>
				<script nonce="${nonce}" type="text/javascript" src="${sourceJs}"></script>
			</body>
		</html>
	`;
}

function getNonce() {
	let text = '';
	let possible = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
	for (let i = 0; i < 32; i++) {
		text += possible.charAt(Math.floor(Math.random() * possible.length));
	}
	return text;
}